ThesisToolBox/urls.py
from rest_api.views import *
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from rest_framework import routers
from.views import *


router = routers.DefaultRouter()
router.register(r'persons', PersonViewSet)
router.register(r'notes', NoteViewSet)
router.register(r'tags', TagViewSet)
router.register(r'sources', SourceViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', Index.as_view(), name='index'),
    url('^sources/', include('source_tracker.urls', namespace='sourcetracker')),
    url('^persons/', include('person_tracker.urls', namespace='persontracker')),
    url('^notes/', include('notes.urls', namespace='notes')),
    url('^scraper/', include('hansardscraper.urls', namespace='scraper')),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/',include(router.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

notes/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^tags/$', TagOverview.as_view(), name='tag_overview'),
    url('^tag/(?P<pk>[0-9]+)/$', TagDetail.as_view(), name='tag_detail'),
    url('^tags/create/$', TagCreate.as_view(), name='tag_create'),

    url('^todo/$', TodoView.as_view(), name='todo'),

    url('^create-note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', TagNoteAdd.as_view(), name='tag_create_note'),
    url('^(?P<pk>[0-9]+)/$', NoteDetail.as_view(), name='note-detail'),
    url('^(?P<pk>[0-9]+)/update/$', NoteUpdateView.as_view(), name='tag_note_update'),

]

person_tracker/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^$', Home.as_view(), name='person_tracker_home'),
    url('^(?P<pk>[0-9]+)/$', PersonDetail.as_view(), name='person_detail'),
    url('^(?P<pk>[0-9]+)/update/$', PersonUpdate.as_view(), name='person_update'),
    url('^add-person/', PersonCreate.as_view(), name='person_create'),
    url('^add-nationality/', NationalityCreate.as_view(), name='nationality_create'),
    url('^create_note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', PersonNoteAdd.as_view(), name='person_create_note'),
]

source_tracker/urls.py
from django.conf.urls import url
from .views import *
from notes.views import NoteUpdateView

urlpatterns = [
    url('^$', Home.as_view(), name='source_tracker_home'),
    url('^create/', SourceCreate.as_view(), name='source_create'),

    url('^(?P<pk>[0-9]+)/$', SourceDetail.as_view(), name='source_detail'),
    url('^(?P<pk>[0-9]+)/update/$', SourceUpdate.as_view(), name='source_update'),

       url('^create_note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', SourceNoteAdd.as_view(), name='source_create_note'),
]

notes/models.py
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.db import models
from tinymce import models as tinymce_models


class Thesis(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.name


class Tag(models.Model):
    added_on = models.DateTimeField(default=timezone.now, editable=True)
    name = models.CharField(max_length=300)
    notes = GenericRelation('Note', blank=True, null=True, related_name='notes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    active = models.BooleanField(default=True)
    #thesis = models.ForeignKey(Thesis)

    def __str__(self):
        return self.name


class Note(models.Model):
    added_on = models.DateTimeField(default=timezone.now, editable=True)
    content = tinymce_models.HTMLField()
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    tags = models.ManyToManyField(Tag, blank=True, related_name='note_tags')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    active = models.BooleanField(default=True)
    #thesis = models.ForeignKey(Thesis)

    def __str__(self):
        return self.content[:30]

notes/views.py
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .utils import tag_dict_generator
from .models import Tag, Note
from source_tracker.models import Source
from django.apps import apps


class TodoView(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'base/todo.html'


class BaseNoteCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Note
    fields = ['content', 'tags']

    def form_valid(self, form, *args, **kwargs):
        form.instance.user = self.request.user
        self.model = self.kwargs['model']
        self.app = self.kwargs['app']
        self.key = self.kwargs['model_pk']
        self.model_object = apps.get_model(self.app, self.model)
        self.linked_object = self.model_object.objects.get(pk=self.key)
        form.instance.content_object = self.linked_object

        #check if tag is in linked object tags
        #Add tag if this is not the case.
        tags = form.cleaned_data['tags']

        #Tag objects cannot have tags, so skipp this part if the 'linked_object'
        #is a tag.
        if self.linked_object.__class__.__name__ == 'Tag':
            pass
        else:
            for tag in tags:
                if tag in self.linked_object.tags.all():
                    pass
                else:
                    self.linked_object.tags.add(tag)

        return super().form_valid(form)


class NoteUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Note
    fields = ['content', 'tags']
    template_name = "base/generic_form.html"
    success_url = reverse_lazy('notes:tag_overview')


class TagOverview(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Tag
    template_name = 'notes/tag_overview.html'

    def get_queryset(self):
        qs = Tag.objects.filter(user=self.request.user)
        return qs


class TagDetail(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    model = Tag
    template_name = 'notes/tag_detail.html'

    def get_context_data(self, **kwargs):
        data = super(TagDetail, self).get_context_data(**kwargs)
        #Generate filtered dict with Sources as keys and the linked comments
        #as values.
        linked_Sources = Source.objects.filter(
            tags__id=self.object.pk,
            user=self.request.user
        ).order_by('-pk')
        data['notes'] = tag_dict_generator(linked_Sources, self)
        return data


class NoteDetail(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    model = Note
    template_name = 'notes/note_detail.html'


class TagCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Tag
    template_name = 'base/generic_form.html'
    fields = ['name']
    success_url = reverse_lazy('notes:tag_overview')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TagNoteAdd(BaseNoteCreateView):
    template_name = "base/generic_form.html"
    success_url = reverse_lazy('notes:tag_overview')

templates/notes/note_detail.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
<h1>Note Detail</h1>
<a href="{% url 'notes:tag_note_update' pk=object.pk %}">Edit</a>
    <b> {{object.added_on}}</b>
    {{ object.content|safe }}
    <hr>
    <h4>Tags:</h4>
    <hr>
    {% for tag in note.tags.all %}
        <a href="{% url 'notes:tag_detail' pk=tag.pk %}">{{ tag }}</a> <br>
    {% endfor %}
</div>
{% endblock %}

templates/notes/note_section.html
{% if object.notes %}
<h2>Notes:</h2>
{% for note in object.notes.all %}
    <a href="{% url 'notes:note_update' pk=note.pk %}">Edit</a>
    <b> {{note.added_on}}</b>
    {{ note.content|safe }}
    {% for tag in note.tags.all %}
        <a href="{% url 'notes:tag_detail' pk=tag.pk %}">{{ tag }}</a> <br>
    {% endfor %}
    <br>
    <hr>
{% endfor %}
{% endif %}

templates/notes/notes_overview.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
<h1>Jeej NOTEOVERVIEWhome</h1>
    <a href="{% url 'notes:note_create' %}">create new</a>
    {% for note in object_list %}
    <ul>
    <li><a href="{% url 'notes:note_detail' pk=note.pk%}">{{note.name}}</a></li>
    </ul>
    {% endfor %}

</div>
{% endblock %}

templates/notes/own_notes_section.html
{% if object.notes %}
    <h2>General Notes:</h2>
    {% for note in object.notes.all %}
        <b> {{note.added_on}}</b>
        <a href="{% url 'notes:tag_note_update' pk=note.id %}">Edit</a>
        {{ note.content|safe }}
        {% for tag in note.tags.all %}
            | <a href="{% url 'notes:tag_detail' pk=tag.pk %}">{{ tag }}</a> | <br>
        {% endfor %}
        <br>
        <hr>
    {% endfor %}
{% endif %}

templates/notes/source_note_section.html
{% if notes.items %}
    <h3>Tags:</h3>
    {% for key, set in notes.items %}
        <a href="{% url 'notes:tag_detail' pk=set.0.id %}"><h2>{{set.0.name}}</h2></a>
        {% for note in set|slice:"1:" %}
            <b>{{ note.added_on }}</b>
            {{ note.content|safe}}
            {%for tag in note.linked_tags%} <a href="{% url 'notes:tag_detail' pk=tag.id %}">| {{tag.name}} |</a>{% endfor %}
            <hr>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/notes/tag_detail.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
<h1>{{ object.name }} - Tag Detail</h1>
<a href="{% url 'notes:tag_create_note' 'tag' 'notes' object.pk %}">create note</a>

{% if persons %}
<h2>Persons:</h2>
    <ul>
    {% for person in persons %}
        <li><a href="{% url 'persontracker:person_detail' pk=person.pk %}">{{person.full_name}}</a></li>
    {% endfor %}
    </ul>
{% endif %}


{% include 'notes/own_notes_section.html'%}
{% include 'notes/tag_note_section.html'%}


</div>
{% endblock %}

templates/notes/tag_note_section.html
{% if notes.items %}
    <h3>Sources:</h3>
    {% for key, set in notes.items %}
        <a href="{% url 'sourcetracker:source_detail' pk=set.0.id %}"><h4>{{set.0.title}}</h4></a>
        <br><b>{{set.0.hashed_author.name}} - {{set.0.publication_date}</b><br>
        {% for note in set|slice:"1:" %}
            <b>{{ note.added_on }}</b>
            <a href="{% url 'notes:tag_note_update' pk=note.id %}">Edit</a>
            {{ note.content|safe}}
            {%for tag in note.linked_tags%} | <a href="{% url 'notes:tag_detail' pk=tag.id %}">{{tag.name}}</a> |   {% endfor %}
            <hr>
        {% endfor %}
    <hr>
    {% endfor %}
{% endif %}

templates/notes/tag_overview.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
<h1>Tags</h1>
    <a href="{% url 'notes:tag_create' %}">create new</a>
    <ul>
    {% for tag in object_list %}
    <li><a href="{% url 'notes:tag_detail' pk=tag.pk%}">{{tag.name}}</a></li>
    {% endfor %}
    </ul>
</div>
{% endblock %}