ThesisToolBox/urls.py
from rest_api.views import *
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from rest_framework import routers
from.views import *


router = routers.DefaultRouter()
router.register(r'persons', PersonViewSet)
router.register(r'notes', NoteViewSet)
router.register(r'tags', TagViewSet)
router.register(r'sources', SourceViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', Index.as_view(), name='index'),
    url('^sources/', include('source_tracker.urls', namespace='sourcetracker')),
    url('^persons/', include('person_tracker.urls', namespace='persontracker')),
    url('^notes/', include('notes.urls', namespace='notes')),
    url('^scraper/', include('hansardscraper.urls', namespace='scraper')),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/',include(router.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

hansardscraper/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^favorites/$',
        FavoritesListView.as_view(),
        name='favorites'
        ),
    url('^create-note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$',
        FavoriteNoteAdd.as_view(),
        name='favorite_create_note'
        ),
    url('^searches/$',
        SearchListView.as_view(),
        name='search_overview'
        ),
    url('^searches/(?P<pk>[0-9]+)/$',
        SearchDetailView.as_view(),
        name='search_detail'
        ),
    url('^quote/(?P<pk>[0-9]+)/$',
        QuoteDetailView.as_view(),
        name='quote_detail'
        ),
    url('^debate/(?P<pk>[0-9]+)/$',
        DebateDetailView.as_view(),
        name='debate_detail'
        ),
    url('^session/(?P<pk>[0-9]+)/$',
        SessionDetailView.as_view(),
        name='session_detail'
        ),
    url('^speaker/(?P<pk>[0-9]+)/$',
        SpeakerDetailView.as_view(),
        name='speaker_detail'
        ),
]

notes/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^tags/$', TagOverview.as_view(), name='tag_overview'),
    url('^tag/(?P<pk>[0-9]+)/$', TagDetail.as_view(), name='tag_detail'),
    url('^tags/create/$', TagCreate.as_view(), name='tag_create'),

    url('^todo/$', TodoView.as_view(), name='todo'),

    url('^create-note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', TagNoteAdd.as_view(), name='tag_create_note'),
    url('^(?P<pk>[0-9]+)/$', NoteDetail.as_view(), name='note-detail'),
    url('^(?P<pk>[0-9]+)/update/$', NoteUpdateView.as_view(), name='tag_note_update'),

]

person_tracker/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^$', Home.as_view(), name='person_tracker_home'),
    url('^(?P<pk>[0-9]+)/$', PersonDetail.as_view(), name='person_detail'),
    url('^(?P<pk>[0-9]+)/update/$', PersonUpdate.as_view(), name='person_update'),
    url('^add-person/', PersonCreate.as_view(), name='person_create'),
    url('^add-nationality/', NationalityCreate.as_view(), name='nationality_create'),
    url('^create_note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', PersonNoteAdd.as_view(), name='person_create_note'),
]

source_tracker/urls.py
from django.conf.urls import url
from .views import *
from notes.views import NoteUpdateView

urlpatterns = [
    url('^$', Home.as_view(), name='source_tracker_home'),
    url('^create/', SourceCreate.as_view(), name='source_create'),

    url('^(?P<pk>[0-9]+)/$', SourceDetail.as_view(), name='source_detail'),
    url('^(?P<pk>[0-9]+)/update/$', SourceUpdate.as_view(), name='source_update'),

       url('^create_note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', SourceNoteAdd.as_view(), name='source_create_note'),
]

templates/base/base.html
{% load analytical %}
{% load static %}
{% load staticfiles %}
<html>
<head>
{% analytical_head_top %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link rel="stylesheet" type='text/css' href="{% static 'interface/css/base.css' %}">
{% block head %}
{% endblock %}
{% analytical_head_bottom %}
</head>

<body>
{% analytical_body_top %}
<header>
    <ul>
        <li><a href="{% url 'index' %}">Letsgohome</a></li>
        <li><a href="{% url 'sourcetracker:source_tracker_home' %}">SOURCE</a></li>
        <li><a href="{% url 'persontracker:person_tracker_home' %}">PERSONS</a></li>
        <li><a href="{% url 'notes:tag_overview' %}">TAGS</a></li>
        <li><a href="{% url 'scraper:search_overview' %}">SEARCHES</a></li>
        <li><a href="{% url 'scraper:favorites' %}">Favorites</a></li>
    </ul>
</header>
{% block content %}
{% endblock %}
{% analytical_body_bottom %}
</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>

templates/base/generic_form.html
{% extends 'base/base.html' %}
{% load static %}
{% block head %}
<script src="{% static 'js/tinymce/tinymce.min.js' %}" /></script>
<script>tinymce.init({ selector:'textarea' });</script>
{{ form.media }}
{% endblock %}
{% block content %}
<div class="container">
<form method="post">
{% csrf_token %}
    {{ form.as_p }}
</form>
</div>
{% endblock %}

templates/base/todo.html
<h1>MAIN ISSUES</h1>
<ul>
<li>Note maken selecteert niet de tags</li>
<li>Note maken kan zonder tags, moet niet mogen</li>
<li>Vind manier om de lijsten te filteren. </li>
<li>Als je een note maakt op een object, moet het object de tag overnemen</li>
<li>Publicatie datums naar year only zetten</li>
<li>Date of birth unknown info optie geven (vooral voor autheyrs)</li>
<li>Check ondersteuning van meerdere auteurs</li>
<li>Historian / Author tag die je kan checken</li>
</ul>






tag overview, toon sources/ persons onder elke tag list entry

'select or add' bij het assignen van bepaalde foreignkey objecten

publishers als los object