ThesisToolBox/urls.py
from rest_api.views import *
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from rest_framework import routers
from.views import *


router = routers.DefaultRouter()
router.register(r'persons', PersonViewSet)
router.register(r'notes', NoteViewSet)
router.register(r'tags', TagViewSet)
router.register(r'sources', SourceViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', Index.as_view(), name='index'),
    url('^sources/', include('source_tracker.urls', namespace='sourcetracker')),
    url('^persons/', include('person_tracker.urls', namespace='persontracker')),
    url('^notes/', include('notes.urls', namespace='notes')),
    url('^scraper/', include('hansardscraper.urls', namespace='scraper')),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/',include(router.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

hansardscraper/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^favorites/$',
        FavoritesListView.as_view(),
        name='favorites'
        ),
    url('^create-note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$',
        FavoriteNoteAdd.as_view(),
        name='favorite_create_note'
        ),
    url('^searches/$',
        SearchListView.as_view(),
        name='search_overview'
        ),
    url('^searches/(?P<pk>[0-9]+)/$',
        SearchDetailView.as_view(),
        name='search_detail'
        ),
    url('^quote/(?P<pk>[0-9]+)/$',
        QuoteDetailView.as_view(),
        name='quote_detail'
        ),
    url('^debate/(?P<pk>[0-9]+)/$',
        DebateDetailView.as_view(),
        name='debate_detail'
        ),
    url('^session/(?P<pk>[0-9]+)/$',
        SessionDetailView.as_view(),
        name='session_detail'
        ),
    url('^speaker/(?P<pk>[0-9]+)/$',
        SpeakerDetailView.as_view(),
        name='speaker_detail'
        ),
]

notes/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^tags/$', TagOverview.as_view(), name='tag_overview'),
    url('^tag/(?P<pk>[0-9]+)/$', TagDetail.as_view(), name='tag_detail'),
    url('^tags/create/$', TagCreate.as_view(), name='tag_create'),

    url('^todo/$', TodoView.as_view(), name='todo'),

    url('^create-note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', TagNoteAdd.as_view(), name='tag_create_note'),
    url('^(?P<pk>[0-9]+)/$', NoteDetail.as_view(), name='note-detail'),
    url('^(?P<pk>[0-9]+)/update/$', NoteUpdateView.as_view(), name='tag_note_update'),

]

hansardscraper/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from fuzzywuzzy import fuzz


class URL(models.Model):
    url = models.URLField()
    checked = models.BooleanField(default=False)


class Speaker(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField(blank=True, null=True)

    @property
    def debates(self):
        debates = Debate.objects.filter(quotes__in=self.quotes.all())
        return debates.distinct()

    @property
    def sessions(self):
        sessions = Session.objects.filter(debates__in=self.debates)
        return sessions.distinct()

    def __str__(self):
        return self.name


class Session(models.Model):
    TYPE_CHOICES = (
        ('com', 'house of commons'),
        ('lrd', 'house of lords'),
    )
    type = models.CharField(choices=TYPE_CHOICES, max_length=3)
    date = models.DateTimeField()
    url = models.URLField()

    @property
    def speakers(self):
        linked_quotes = BlockQuote.objects.filter(debate__in=self.debates.all())
        speakers = Speaker.objects.filter(quotes__in=linked_quotes)
        return speakers.distinct()

    def __str__(self):
        return "session on %s" % self.date


class Debate(models.Model):
    session = models.ForeignKey(Session, related_name='debates')
    title = models.CharField(max_length=400)
    url = models.URLField()
    favorited = models.BooleanField(default=False)
    read = models.BooleanField(default=False)
    notes = GenericRelation('notes.note', blank=True, null=True, related_name='notes')

    @property
    def speakers(self):
        speakers = Speaker.objects.filter(quotes__in=self.quotes.all())
        return speakers.distinct()

    def __str__(self):
        return self.title


class BlockQuote(models.Model):
    debate = models.ForeignKey(Debate, related_name='quotes')
    speaker = models.ForeignKey(Speaker, related_name='quotes')
    text = models.TextField()
    favorited = models.BooleanField(default=False)
    read = models.BooleanField(default=False)
    notes = GenericRelation('notes.note', blank=True, null=True, related_name='notes')

    def __str__(self):
        return "quote %d - %s" % (self.pk, self.debate.title)


class Search(models.Model):
    started = models.DateTimeField(auto_now_add=True)
    completed = models.DateTimeField(null=True)
    finished = models.BooleanField(default=False)

    @property
    def linked_query(self):
        """
        There can only be one
        At least, I hope - because it will crash otherwise
        """
        if self.primitive_query:
            return self.primitive_query.first()

    def __str__(self):
        return 'search on ' + str(self.started)


class SimpleQuery(models.Model):
    search = models.ForeignKey(Search, related_name='simple_query')
    term = models.CharField(max_length=200)
    results = models.ManyToManyField(
        BlockQuote,
        through='SimpleQueryParams',
        blank=True
    )

    def __str__(self):
        return 'SimpleSearchQuery__' + str(self.search)


class PrimitiveQuery(models.Model):
    search = models.ForeignKey(Search, related_name='primitive_query')
    term = models.CharField(max_length=200)

    @property
    def number_of_results(self):
        """
        :return: number of results linked to this query
        """
        return self.results.all().count()

    def __str__(self):
        return 'PrimitiveSearchQuery__' + str(self.search)


class Query(models.Model):
    search = models.ForeignKey(Search, related_name='query')
    terms = models.CharField(max_length=200)
    results = models.ManyToManyField(
        BlockQuote,
        through='QueryParams',
        blank=True
    )
    started = models.DateTimeField(auto_now_add=True)
    completed = models.DateTimeField(blank=True, null=True)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return str(self.terms)


class SimpleQueryParams(models.Model):
    quote = models.ForeignKey(BlockQuote)
    query = models.ForeignKey(SimpleQuery)
    created = models.DateTimeField(auto_now_add=True)


class QueryParams(models.Model):
    quote = models.ForeignKey(BlockQuote)
    query = models.ForeignKey(Query)
    matches = models.IntegerField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)


class PrimitiveQueryResult(models.Model):
    quote = models.ForeignKey(BlockQuote)
    query = models.ForeignKey(PrimitiveQuery, related_name='results')
    created = models.DateTimeField(auto_now_add=True)
    excerpt = models.TextField(blank=True, null=True)
    seen = models.BooleanField(default=False)
    useful = models.NullBooleanField(blank=True, null=True, default=None)

    def __str__(self):
        return self.query.term + ' ' + str(self.quote.pk)

    def create_excerpt(self):
        """
        Creates excerpts from matches, for quick scanning
        :return: excerpts, with matching words capitalized
        """
        excerpts = ""
        query = self.query.term
        text = self.quote.text
        split_text = text.split()
        for word in split_text:
            if fuzz.ratio(word.lower(), query.lower()) > 88:
                # if word.lower() == query.lower():
                index = split_text.index(word)
                # Capitalize matched term, so its easier to read
                split_text[index] = word.upper()
                # Create excerpts
                excerpts += ' '.join(split_text[index - 40: index + 40])
                excerpts += "\n\n=========\n\n"
        self.excerpt = excerpts
        self.save()

hansardscraper/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from .models import Search, BlockQuote, Debate, Session, Speaker
from hansardscraper.tasks import perform_query
from notes.views import BaseNoteCreateView


class FavoriteNoteAdd(BaseNoteCreateView):
    template_name = "base/generic_form.html"
    success_url = reverse_lazy('scraper:favorites')


class FavoritesListView(LoginRequiredMixin, TemplateView):
    login_url = '/login/'
    template_name = 'hansardscraper/favorites.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['quotes'] = BlockQuote.objects.filter(favorited=True)
        data['debates'] = Debate.objects.filter(favorited=True)
        return data


class SearchListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    template_name = 'hansardscraper/search_list.html'
    model = Search

    def post(self, request):
        text = self.request.POST.get('search-query', None)
        if text != None:
            perform_query.delay(text)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class SearchDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    template_name = 'hansardscraper/search_detail.html'
    model = Search


class QuoteDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    template_name = 'hansardscraper/quote.html'
    model = BlockQuote

    def post(self, request, pk):
        item = self.get_object()
        item.favorited = True
        item.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class DebateDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    template_name = 'hansardscraper/debate_detail.html'
    model = Debate

    def post(self, request, pk):
        item = self.get_object()
        item.favorited = True
        item.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


class SessionDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    template_name = 'hansardscraper/session_detail.html'
    model = Session


class SpeakerDetailView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    template_name = 'hansardscraper/speaker_detail.html'
    model = Speaker

templates/hansardscraper/debate_detail.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div>
            <h1>Debate Detail - Title: {{ object.title }} </h1>
            <b>Date: {{ object.session.date }}</b>
            <br>
            <a href="{% url 'scraper:session_detail' pk=object.session.pk %}">Session: {{ object.session }}</a>
            </br>
            <form class="col-md-5 " method="post" action="">
                {% csrf_token %}
                <div class="input-group">
                    <button name="favorite" value="true"> Favorite</button>
                </div>
            </form>
            <a href="{% url 'scraper:favorite_create_note' 'debate' 'hansardscraper' object.pk %}">create note</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <h3>Quotes:</h3>
            <ul>
            {% for quote in object.quotes.all %}
                <li><a href="{% url 'scraper:quote_detail' pk=quote.pk %}">{{ quote }}</a></li>
            {% endfor %}
        </div>
        <div class="col-md">
            <h3>Speakers:</h3>
            <ul>
            {% for speaker in object.speakers.all %}
                <li><a href="{% url 'scraper:speaker_detail' pk=speaker.pk %}">{{ speaker }}</a></li>
            {% endfor %}
            </ul>
        </div>
    </div>
    <h4>Notes</h4>
        {% for note in object.notes.all %}
            <b>{{ note.added_on }}</b>
            {{ note.content|safe}}
            {% for tag in note.tags.all %}
            | <a href="{% url 'notes:tag_detail' pk=tag.pk %}">{{ tag }}</a> | <br>
            {% endfor %}
            <hr>
        {% endfor %}
</div>
{% endblock %}

templates/hansardscraper/favorites.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md">
            <h3>Quotes</h3>
            {% for quote in quotes %}
                <h4><a href="{% url 'scraper:quote_detail' pk=quote.pk %}">{{ quote }}</a> - <b>{{ quote.debate.session.date}}</b></h4>
            {% endfor %}
        </div>
        <div class="col-md">
            <h3>Debates</h3>
            {% for debate in debates %}
                <h4><a href="{% url 'scraper:debate_detail' pk=debate.pk %}">{{ debate }}</a> - <b>{{ debate.session.date}}</b></h4>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/hansardscraper/quote.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div>
            <h1><a href="#">{{ object.debate.title }}</a></h1>
            <a href="{% url 'scraper:debate_detail' pk=object.debate.pk %}">Debate</a>
            <form class="col-md-5 " method="post" action="">
                {% csrf_token %}
                <div class="input-group">
                    <button name="favorite" value="true"> Favorite</button>
                </div>
                <a href="{% url 'scraper:favorite_create_note' 'quote' 'hansardscraper' object.pk %}">create note</a>
            </form>
            <p>{{ object.text|linebreaks }}</p>
        </div>
        <hr>
    </div>
    <h4>Notes</h4>
        {% for note in object.notes.all %}
            <b>{{ note.added_on }}</b>
            {{ note.content|safe}}
            {% for tag in note.tags.all %}
            | <a href="{% url 'notes:tag_detail' pk=tag.pk %}">{{ tag }}</a> | <br>
            {% endfor %}
            <hr>
        {% endfor %}
</div>
{% endblock %}

templates/hansardscraper/search_detail.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div>
            <h1>Search Detail - Term: {{ object.linked_query.term }} </h1>
            <br>
            <ul>
            {% for result in object.linked_query.results.all %}

                <li>
                <h3><a href="{% url 'scraper:quote_detail' pk=result.quote.pk %}">{{ result }}</a> - <b>{{ result.quote.debate.session.date}}</b></h3>
                <br>
                {{ result.excerpt|linebreaks }}
                </li>

            {% endfor %}
            </ul>
            <br>


        </div>
    </div>
</div>
{% endblock %}

templates/hansardscraper/search_list.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <form class="col-md-5 " method="post" action="">
            {% csrf_token %}
            <input type="text" name="search-query">
            <input type="submit" value="Primitive Query">
        </form>
        <div>
            <h1>Search List</h1>
            <ul >
            {% for search in object_list %}
                <li
                {% if not search.finished %} style="background-color:FFAAAA;" {% else %} style="background-color:97D38D;" {% endif %}>
                {% for query in search.primitive_query.all %}
                    <a href="{% url 'scraper:search_detail' pk=search.pk %}">{{ query.term }}</a> - {{ query.number_of_results }} results.</li>
                {% endfor %}
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/hansardscraper/session_detail.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div>
            <h1>Session Detail</h1>
            <b>Date: {{ object.date }} | Type: {{ object.type }}</b>
            <a href="{{ object.url }}">Link</a>
            <br>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <h3>Debates:</h3>
            <ul>
            {% for debate in object.debates.all %}
                <li><a href="{% url 'scraper:debate_detail' pk=debate.pk %}">{{ debate }}</a></li>
            {% endfor %}
        </div>
        <div class="col-md">
            <h3>Speakers:</h3>
            <ul>
            {% for speaker in object.speakers.all %}
                <li><a href="{% url 'scraper:speaker_detail' pk=speaker.pk %}">{{ speaker }}</a></li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/hansardscraper/speaker_detail.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div>
            <h1>Speaker Detail - {{ object }}</h1>
            <br>
        </div>
    </div>
    <div class="row">
        <div class="col-md">
            <h3>Quotes:</h3>
            <ul>
            {% for quote in object.quotes.all %}
                <li><a href="{% url 'scraper:quote_detail' pk=quote.pk %}">{{ quote }}</a></li>
            {% endfor %}
        </div>
        <div class="col-md">
            <h3>Debates:</h3>
            <ul>
            {% for debate in object.debates.all %}
                <li><a href="{% url 'scraper:debate_detail' pk=debate.pk %}">{{ debate }}</a></li>
            {% endfor %}
            </ul>
        </div>
        <div class="col-md">
            <h3>Sessions:</h3>
            <ul>
            {% for session in object.sessions.all %}
                <li><a href="{% url 'scraper:session_detail' pk=session.pk %}">{{ session }}</a></li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}