ThesisToolBox/urls.py
from rest_api.views import *
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from rest_framework import routers
from.views import *


router = routers.DefaultRouter()
router.register(r'persons', PersonViewSet)
router.register(r'notes', NoteViewSet)
router.register(r'tags', TagViewSet)
router.register(r'sources', SourceViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', Index.as_view(), name='index'),
    url('^sources/', include('source_tracker.urls', namespace='sourcetracker')),
    url('^persons/', include('person_tracker.urls', namespace='persontracker')),
    url('^notes/', include('notes.urls', namespace='notes')),
    url('^scraper/', include('hansardscraper.urls', namespace='scraper')),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/',include(router.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

notes/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^tags/$', TagOverview.as_view(), name='tag_overview'),
    url('^tag/(?P<pk>[0-9]+)/$', TagDetail.as_view(), name='tag_detail'),
    url('^tags/create/$', TagCreate.as_view(), name='tag_create'),

    url('^todo/$', TodoView.as_view(), name='todo'),

    url('^create-note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', TagNoteAdd.as_view(), name='tag_create_note'),
    url('^(?P<pk>[0-9]+)/$', NoteDetail.as_view(), name='note-detail'),
    url('^(?P<pk>[0-9]+)/update/$', NoteUpdateView.as_view(), name='tag_note_update'),

]

person_tracker/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url('^$', Home.as_view(), name='person_tracker_home'),
    url('^(?P<pk>[0-9]+)/$', PersonDetail.as_view(), name='person_detail'),
    url('^(?P<pk>[0-9]+)/update/$', PersonUpdate.as_view(), name='person_update'),
    url('^add-person/', PersonCreate.as_view(), name='person_create'),
    url('^add-nationality/', NationalityCreate.as_view(), name='nationality_create'),
    url('^create_note/(?P<model>[a-zA-Z]+)/(?P<app>[a-zA-Z_]+)/(?P<model_pk>[0-9]+)/$', PersonNoteAdd.as_view(), name='person_create_note'),
]

person_tracker/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from notes.models import Note, Tag
# Create your models here.

class Nationality(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        verbose_name_plural = "nationalities"

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class Person(models.Model):
    firstname = models.CharField(max_length=255)
    middlename = models.CharField(max_length=255, blank=True)
    lastname = models.CharField(max_length=255)
    added_on = models.DateTimeField(default=timezone.now, editable=True)
    year_of_birth = models.DateField(blank=True, null=True)
    year_of_death = models.DateField(blank=True, null=True)
    nationality = models.ForeignKey(Nationality, blank=True, null=True)
    branch = models.CharField(max_length=255)
    notes = GenericRelation(Note, null=True, blank=True, related_query_name='notes')
    tags = models.ManyToManyField(Tag, blank=True, related_name='person_tags')
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    historian = models.BooleanField(default=False)

    @property
    def full_name(self):
        return self.firstname + " " + self.middlename + " " + self.lastname

    def __str__(self):
        return self.full_name

person_tracker/forms.py
from django.forms import ModelForm, SelectDateWidget
from person_tracker.models import Person, Nationality

class PersonForm(ModelForm):

    class Meta:
        model = Person
        fields = ['firstname', 'middlename', 'lastname', 'year_of_birth', 'year_of_death', 'nationality', 'branch', 'historian', 'tags']
        widgets = {
            'year_of_birth': SelectDateWidget(years=range(1800, 2018)),
            'year_of_death': SelectDateWidget(years=range(1800, 2018)),
        }

person_tracker/views.py
from django.shortcuts import render
from django.apps import apps
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from person_tracker.models import Person, Nationality
from person_tracker.forms import PersonForm
from notes.views import BaseNoteCreateView



class Home(LoginRequiredMixin, ListView):
    #template_name = "person_tracker/person_tracker_home.html"
    login_url = '/login/'
    model = Person
    template_name = "person_tracker/person_overview.html"

    def get_queryset(self):
        qs = Person.objects.filter(user=self.request.user)
        return qs


class PersonCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Person
    success_url = reverse_lazy('persontracker:person_tracker_home')
    form_class = PersonForm
    template_name = "person_tracker/person_create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PersonUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Person
    form_class = PersonForm
    template_name = 'person_tracker/person_create.html'
    success_url = reverse_lazy('persontracker:person_tracker_home')


class PersonDetail(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    model = Person
    template_name = "person_tracker/person_detail.html"
    context_object_name = 'actor'


class PersonNoteAdd(BaseNoteCreateView):
    login_url = '/login/'
    template_name = "person_tracker/generic_form.html"
    success_url = reverse_lazy('persontracker:person_tracker_home')


class PersonNoteUpdate():
    login_url = '/login/'
    pass


class NationalityCreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Nationality
    success_url = reverse_lazy('persontracker:person_tracker_home')
    fields = ['name']
    template_name = "person_tracker/nationality_create.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class NationalityOverview(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = Person
    template_name = "person_tracker/nationality_overview.html"

    def get_queryset(self):
        qs = Person.objects.filter(user=self.request.user)
        return qs

templates/person_tracker/generic_form.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

</div>
{% endblock %}

templates/person_tracker/nationality_create.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

</div>
{% endblock %}

templates/person_tracker/nationality_overview.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
<h1>Jeej NATIONALITYOVERVIEW</h1>

</div>
{% endblock %}

templates/person_tracker/person_create.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

</div>
{% endblock %}

templates/person_tracker/person_detail.html
{% extends 'base/base.html' %}
    {% block content %}
    <div class="container">
    <h1>{{object.full_name}} - Person Detail</h1>
    <a href="{% url 'persontracker:person_update' pk=object.pk %}">Update</a>
    <a href="{% url 'persontracker:person_create_note' 'person' 'person_tracker' object.pk %}">create note</a>

    {% include 'notes/own_notes_section.html'%}
    {% include 'notes/note_section.html' %}

    </div>
{% endblock %}

templates/person_tracker/person_overview.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
<h1>Persons</h1>
    <a href="{% url 'persontracker:person_create' %}">Add person</a>
    <a href="{% url 'persontracker:nationality_create' %}">Add nationality</a>

    <ul>
    {% for object in object_list %}
        <li><a href="{% url 'persontracker:person_detail' pk=object.pk %}">{{ object.full_name }}</a></li>
    {% endfor %}
    </ul>

 </div>
{% endblock %}

templates/person_tracker/person_tracker_home.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
<h1>Jeej personOVERVIEWhome</h1>
    <a href="{% url 'persontracker:person_create' %}">Add person</a>

    <ul>
    {% for object in object_list %}
        <li>{{ object.full_name }}</li>
    {% endfor %}
    </ul>

</div>
{% endblock %}